models/Siswa.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "siswa".
 *
 * @property int $id
 * @property int $id_user
 * @property string $pendidikan_terakhir
 * @property string $jurusan
 * @property string $status 'mendaftar, diterima,proses, lulus'
 *
 * @property AbsensiSiswa[] $absensiSiswas
 * @property Pembayaran[] $pembayarans
 * @property User $user
 * @property SiswaKursus[] $siswaKursuses
 */
class Siswa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'siswa';
    }

    public $fotoKtp;

    const PATH_ = 'web/upload/siswa/';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'pendidikan_terakhir', 'jurusan', 'status'], 'required'],
            [['id_user'], 'integer'],
            [['pendidikan_terakhir', 'status', 'foto_ktp'], 'string', 'max' => 20],
            [['jurusan'], 'string', 'max' => 50],
            [['fotoKtp'], 'file',  'extensions' => 'gif, jpg, jpeg, png'],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id_user']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'pendidikan_terakhir' => 'Pendidikan Terakhir',
            'jurusan' => 'Jurusan',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbsensiSiswas()
    {
        return $this->hasMany(AbsensiSiswa::className(), ['id_siswa' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getPembayarans()
    {
        return $this->hasMany(Pembayaran::className(), ['id_siswa' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_user' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswaKursuses()
    {
        return $this->hasMany(SiswaKursus::className(), ['id_siswa' => 'id']);
    }

    public function getPathButktiBayar()
    {
        return $this->getPembayarans();
    }

    public function getPathFoto()
    {
        return $this->user->biodataUsers->foto;
    }

    public function getBasePath()
    {
        return self::PATH_;
    }

    public function getNamaSiswa()
    {
        return $this->user->biodataUsers->nama;
    }

    public function getArrayPendidikanTerakhir()
    {
        return [
            'SMA/SMK sederajat' => 'SMA/SMK sederajat',
            'diploma' =>'Diploma',
            'sarjana' =>'Sarjana',
            'Wed' =>'Rabu',
            'magister' =>'Magister',
        ];
    }

    public function checkWaktuPembayaran($value='')
    {
        $model = SiswaKursus::find()->where(['id_siswa'=>User::getIdSiswa()])->orderBy(['id'=> SORT_DESC])->one();
        $currentDate = date('Y-m-d');
        $currentDate=date_create($currentDate);
        $startDate=date_create($model->tgl_pilih);
        $diff=date_diff($currentDate,$startDate);
        if ($diff->d < 3) {
            return true;
        }else{
            return false;
        }
    }

    public function getSisaWaktuPembayaran()
    {
        $model = SiswaKursus::find()->where(['id_siswa'=>User::getIdSiswa()])->orderBy(['id'=> SORT_DESC])->one();
        $currentDate = date('Y-m-d');
        $currentDate=date_create($currentDate);
        $startDate=date_create($model->tgl_pilih);
        return date_diff($currentDate,$startDate)->d;
    }
}

controllers/SiswaController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Siswa;
use app\models\search\SiswaSearch;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SiswaController implements the CRUD actions for Siswa model.
 */
class SiswaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Siswa models.
     * @return mixed
     */
    public function actionIndex()
    {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Siswa::find(),
        ]);

        return $this->render('index', [
            'dataSiswa' => $dataProvider->getModels(),
        ]);
    }

    /**
     * Displays a single Siswa model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionBuktiTransfer($id)
    {
        return $this->renderAjax('bukti_transfer', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Siswa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Siswa();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Siswa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Siswa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Siswa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Siswa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Siswa::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/siswa/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Siswa */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="siswa-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_ktp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tempat_lahir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tgl_lahir')->textInput() ?>

    <?= $form->field($model, 'jenis_kelamin')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'hp')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pendidikan_terakhir')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'jurusan')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'foto')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/siswa/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\SiswaSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="siswa-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'no_ktp') ?>

    <?= $form->field($model, 'tempat_lahir') ?>

    <?php // echo $form->field($model, 'tgl_lahir') ?>

    <?php // echo $form->field($model, 'jenis_kelamin') ?>

    <?php // echo $form->field($model, 'alamat') ?>

    <?php // echo $form->field($model, 'hp') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'pendidikan_terakhir') ?>

    <?php // echo $form->field($model, 'jurusan') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'foto') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/siswa/bukti_transfer.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Siswa */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Siswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="widget">
            <div class="widget-image widget-image-sm">
                <img src="<?=Yii::$app->homeUrl?>templates/img/placeholders/photos/photo1@2x.jpg" alt="image">
                <div class="widget-image-content text-center">
                    <img src="<?=Yii::$app->homeUrl?>upload/<?=$model->foto?>" alt="avatar" class="img-circle img-thumbnail img-thumbnail-transparent img-thumbnail-avatar-2x push">
                    <h2 class="widget-heading text-light"><strong><?=$model->nama?></strong></h2>
                    <h4 class="widget-heading text-light-op"><em><?=$model->email?></em></h4>
                </div>
            </div>
            <div class="widget-content widget-content-full border-bottom">
                <div class="row text-center">
                    <div class="col-xs-6 push-inner-top-bottom border-right">
                        <h3 class="widget-heading"><i class="gi gi-heart text-danger push"></i> <br><small><strong>1.5k</strong> Favorites</small></h3>
                    </div>
                    <div class="col-xs-6 push-inner-top-bottom">
                        <h3 class="widget-heading"><i class="gi gi-group themed-color-social push"></i> <br><small><strong>58.6k</strong> Followers</small></h3>
                    </div>
                </div>
            </div>
            <div class="widget-content border-bottom">
               <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'no_ktp',
                        'tempat_lahir',
                        'tgl_lahir',
                        'jenis_kelamin',
                        'alamat:ntext',
                        'hp',
                        'pendidikan_terakhir',
                        'jurusan',
                        'status',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>

views/siswa/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Siswa */

$this->title = 'Create Siswa';
$this->params['breadcrumbs'][] = ['label' => 'Siswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="siswa-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/siswa/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use app\models\Siswa;
/* @var $this yii\web\View */
/* @var $searchModel app\models\search\SiswaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Siswa';
$this->params['breadcrumbs'][] = $this->title;

Modal::begin([
        'header'=>'<h4>Detail Siswa</h4>',
        'id'=>'modal',
        'size'=>'modal-lg',
    ]);
echo "<div id='content-modal'></div>";
Modal::end();

// $this->registerJsFile("@web/templates/js/custom.js", ['depends' => 'yii\web\JqueryAsset']);

?>
<div class="siswa-index">
    <div class="block full">
        <div class="block-title">
            <h2>Datatables</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th style="width: 80px;" class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></th>
                        <th>Nama</th>
                        <th>Alamat</th>
                        <th style="width: 320px;">Email</th>
                        <th style="width: 120px;" class="text-center"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dataSiswa as $key => $value) { 
                        $urlView = Url::toRoute(['/siswa/view', 'id' => $value->id]);
                    ?>
                    <tr>
                        <td class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></td>
                        <td><strong><?=strtoupper($value->user->biodataUsers->nama)?></strong></td>
                        <td><?=strtoupper($value->user->biodataUsers->alamat)?></td>
                        <td><?=strtoupper($value->user->email)?></td>
                        <td class="text-center">
                            <?=Html::button('<i class="fa fa-info-circle"></i>', ['value'=>$urlView,'class' => 'btn btn-primary btn-flat btn-modal btn-sm']);?>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>$(function(){ UiTables.init(); });</script>

views/siswa/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Siswa */

$this->title = 'Update Siswa: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Siswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="siswa-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/siswa/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Siswa */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Siswas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="widget">
            <div class="widget-image widget-image-sm">
                <img src="<?=Yii::$app->homeUrl?>templates/img/placeholders/photos/photo1@2x.jpg" alt="image">
                <div class="widget-image-content text-center">
                    <img src="<?=Yii::$app->homeUrl?>/<?=$model->pathFoto?>" alt="avatar" class="img-circle img-thumbnail img-thumbnail-transparent img-thumbnail-avatar-2x push">
                    <h2 class="widget-heading text-light"><strong><?=$model->user->biodataUsers->nama?></strong></h2>
                    <h4 class="widget-heading text-light-op"><em><?=$model->user->email?></em></h4>
                </div>
            </div>
            <div class="widget-content border-bottom">
               <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        [
                            'label'=>'No Ktp',
                            'value'=>$model->user->biodataUsers->no_ktp,
                        ],
                        [
                            'label'=>'Tempat Lahir',
                            'value'=>$model->user->biodataUsers->tempat_lahir,
                        ],
                        [
                            'label'=>'Tanggal Lahir',
                            'value'=>$model->user->biodataUsers->tgl_lahir,
                        ],
                        [
                            'label'=>'Jenis Kelamin',
                            'value'=>$model->user->biodataUsers->jenis_kelamin,
                        ],
                        [
                            'label'=>'Alamat',
                            'value'=>$model->user->biodataUsers->alamat,
                        ],
                        [
                            'label'=>'No Telpn',
                            'value'=>$model->user->biodataUsers->hp,
                        ],
                        'pendidikan_terakhir',
                        'jurusan',
                        'status',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>