controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;
use yii\widgets\ActiveForm;
use app\models\LoginForm;
use app\models\User;
use app\models\BiodataUser;
use app\models\Siswa;
use app\models\ContactForm;
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                // 'actions' => [
                //     'logout' => ['post'],
                // ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'main-login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $modelUser = new User();
        $modelLogin = new LoginForm();
        $modelSiswa = new Siswa();
        $modelBioData = new BiodataUser();
        if ($modelLogin->load(Yii::$app->request->post()) && $modelLogin->login()) {
            return $this->goBack();
        }else{
            return $this->render('login', [
                'modelLogin' => $modelLogin,
                'modelUser'=>$modelUser,
                'modelSiswa'=>$modelSiswa,
                'modelBioData'=>$modelBioData
            ]);
        }
    }

    public function actionRegist()
    {
        
        $modelSiswa = new Siswa();
        $modelUser = new User();
        $modelBioData = new BiodataUser();

        if (Yii::$app->request->isAjax && $modelUser->load(Yii::$app->request->post())) {
                $nm= $_POST['User']['email'];
                $result = User::find()->select(['email'])->where(['email' => "$nm"])->one();
                if ($result) {
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return \yii\widgets\ActiveForm::validate($modelUser, 'email');
                } else {
                    return false;
            }
        }
        $biodataUser = Yii::$app->request->post('BiodataUser');
        $siswa = Yii::$app->request->post('Siswa');
        $user = Yii::$app->request->post('User');

        $modelUser->email = $user['email'];
        $modelUser->password = Yii::$app->security->generatePasswordHash($user['password']);
        $modelUser->status = 1;
        $modelUser->type = 2;

        if (Yii::$app->request->isAjax && $modelBioData->load(Yii::$app->request->post())) {
                $nm= $_POST['BiodataUser']['no_ktp'];
                $result = BiodataUser::find()->select(['no_ktp'])->where(['no_ktp' => "$nm"])->one();
                if ($result) {
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return \yii\widgets\ActiveForm::validate($modelBioData, 'no_ktp');
                } else {
                    return false;
            }
        }

        


        if ($modelUser->save()) {
            $timeFile = strtotime("now");
            $modelSiswa->id_user = $modelUser->id_user;
            $modelSiswa->pendidikan_terakhir = $siswa['pendidikan_terakhir'];
            $modelSiswa->jurusan = $siswa['jurusan'];
            $modelSiswa->status = 'mendaftar';
            $fotoKtp = UploadedFile::getInstanceByName('Siswa[fotoKtp]');
            $pathFotoKtp = Siswa::PATH_.$modelUser->id_user;
            FileHelper::createDirectory($pathFotoKtp, $mode = 0775, $recursive = true);
            $namaFileFotoKtp = $modelUser->id_user.'-'.$timeFile.'-KTP'; 
            $fotoKtp->saveAs($pathFotoKtp ."/". $namaFileFotoKtp . '.' . $fotoKtp->extension);
            $modelSiswa->foto_ktp = $namaFileFotoKtp;

            $modelSiswa->save();

            $modelBioData->id_user = $modelUser->id_user;
            $modelBioData->nama = $biodataUser['nama'];
            $modelBioData->no_ktp = $biodataUser['no_ktp'];
            $modelBioData->tempat_lahir = $biodataUser['tempat_lahir'];
            $modelBioData->tgl_lahir = $biodataUser['tgl_lahir'];
            $modelBioData->jenis_kelamin = $biodataUser['jenis_kelamin'];
            $modelBioData->alamat = $biodataUser['alamat'];
            $modelBioData->hp = $biodataUser['hp'];

            $timeFile = strtotime("now");
            $foto = UploadedFile::getInstanceByName('BiodataUser[file]');
            $path = Siswa::PATH_.$modelUser->id_user;
            
            FileHelper::createDirectory($path, $mode = 0775, $recursive = true);
            $namaFile = $modelUser->id_user.'-'.$timeFile.'-Foto'; 
            
            $foto->saveAs($path ."/". $namaFile . '.' . $foto->extension);
            $modelBioData->foto = $path."/".$namaFile . '.' . $foto->extension;
            
            if ($modelBioData->save()) {
                \Yii::$app->getSession()->setFlash('success', "<i class='fa fa-check-circle'></i> Pendaftaran Telah Berhasil");
                return $this->redirect(['login']);
            }
        }else{
            $this->layout = 'main-login';
            $modelLogin = new LoginForm();
            return $this->render('login', [
                'modelLogin' => $modelLogin,
                'modelUser'=>$modelUser,
                'modelSiswa'=>$modelSiswa,
                'modelBioData'=>$modelBioData
            ]);
        }
    }

    public function actionUsernameValidation()
    {
        $model = new User();
        $modelBioData = new BiodataUser();
        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()) ){
            Yii::$app->response->format ='json';
            return ActiveForm::validate($model);
        }
    }
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Wellcome';
?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\file\FileInput;
use kartik\date\DatePicker;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
// echo Yii::getAlias('@web');
// die;
?>

<div id="login" class="">
    <div id="login-container">
            <!-- Login Header -->
        <h1 class="h2 text-light text-center push-top-bottom animation-pullDown">
            <i class="fa fa-cube text-light-op"></i> <strong>AppUI</strong>
        </h1>
        <?php
            foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
                echo '<div class="alert alert-' . $key . '">' . $message . '</div>';
            }
        ?>
        <!-- END Login Header -->

        <!-- Login Block -->
        <div class="block animation-fadeInQuick">
            <!-- Login Title -->
            <div class="block-title">
                <div class="block-options pull-right">
                    <a href="#" class="btn btn-effect-ripple btn-primary" id="btn-regist" data-toggle="tooltip" data-placement="left" title="Create new account"><i class="fa fa-plus"></i></a>
                </div>
                <h2>Please Login</h2>
            </div>
            <!-- END Login Title -->
            <?php $form = ActiveForm::begin([
                'id' => 'form-login',
                'layout' => 'horizontal',
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-xs-12\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
            ]); ?>

                <?= $form->field($modelLogin, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($modelLogin, 'password')->passwordInput() ?>


               <div class="form-group form-actions">
                    <div class="col-xs-8">
                        <label class="csscheckbox csscheckbox-primary">
                            <input type="checkbox" id="login-remember-me" name="login-remember-me"><span></span> Remember Me?
                        </label>
                    </div>
                    <div class="col-xs-4 text-right">
                        <button type="submit" class="btn btn-effect-ripple btn-sm btn-success">Log In</button>
                        <?= Html::a('Regist', ['#'], ['class'=>'btn btn-effect-ripple btn-sm btn-primary']) ?>
                        <!-- <button type="submit" class="btn btn-effect-ripple btn-sm btn-success">Log In</button> -->
                    </div>
                </div>

            <?php ActiveForm::end(); ?>
            <!-- Social Login -->
            
          
            <!-- END Social Login -->
        </div>
        <!-- END Login Block -->

        <!-- Footer -->
        <footer class="text-muted text-center animation-pullUp">
            <small><span id="year-copy"></span> &copy; <a href="http://goo.gl/RcsdAh" target="_blank">AppUI 2.9</a></small>
        </footer>
        <!-- END Footer -->
    </div>
</div>

<div id="user" class="">
    <div id="regist-container">
        <!-- Register Header -->
        <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
            <a href="#" class="btn btn-effect-ripple btn-primary" id="btn-login" data-toggle="tooltip" data-placement="left" title="Create new account"><i class="fa fa-plus"></i></a> <strong>Create Account</strong>
        </h1>
        <!-- END Register Header -->
                    <?php $form = ActiveForm::begin([
                            'options' => [
                                'class' => 'form-horizontal',
                                'role' => "form"
                            ],
                        'action' => ['site/regist'],
                        'enableAjaxValidation'=>true,
                        // 'validationUrl'=>Url::toRoute('/site/username-validation'),
                        'enableClientValidation'=>true,
                    ]); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="block animation-fadeInQuickInv">

                    <?= $form->field($modelUser, 'email', ['enableAjaxValidation' => true, 'validateOnChange' => true])->textInput(['maxlength' => true]) ?>

                    <?= $form->field($modelUser, 'password')->passwordInput(['maxlength' => true]) ?>

                    <?= $form->field($modelBioData, 'nama')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($modelBioData, 'no_ktp', ['enableAjaxValidation' => true, 'validateOnChange' => true])->textInput(['maxlength' => true]) ?>

                    <?=
                        $form->field($modelSiswa, 'fotoKtp')->widget(FileInput::classname(), [
                            'options' => [
                                'allowedFileExtensions' => ['jpg', 'gif', 'png', 'bmp'],
                            ],
                            'language' => 'en',
                            'pluginOptions' => [
                                'browseClass' => 'btn btn-success',
                                'browseLabel' =>  'Unggah',
                                'showPreview' => true,
                                'showCaption' => true,
                                'showRemove' => true,
                                'showUpload' => false,
                                'required'=>true,
                            ],
                        ])->label('File Ktp')?>

                    <div class="row">
                        <div class="col-md-6">
                            <?= $form->field($modelBioData, 'tempat_lahir')->textInput(['maxlength' => true]) ?>
                            
                        </div>
                        <div class="col-md-6">
                            <?= $form->field($modelBioData, 'tgl_lahir')->widget(DatePicker::classname(), [
                                'options' => ['placeholder' => 'Enter birth date ...'],
                                'pluginOptions' => [
                                    'autoclose'=>true,
                                    'format' => 'yyyy-m-d'
                                ]
                            ]);
                             ?>
                            
                        </div>
                    </div>


                    <?= $form->field($modelBioData, 'jenis_kelamin')->dropDownList(
                                ['laki-laki' => 'Laki-Laki', 'Perempuan' => 'Perempuan']
                        ); ?>

                    <!-- END Register Form -->
                </div>
            </div>
            <div class="col-md-6">
                <div class="block animation-fadeInQuickInv">
                    <?= $form->field($modelBioData, 'alamat')->textarea(['rows' => 6]) ?>
                    <!-- Register Title -->
                    <!-- END Register Title -->

                    <?= $form->field($modelBioData, 'hp')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($modelSiswa, 'pendidikan_terakhir')->dropDownList(
                            $modelSiswa->arrayPendidikanTerakhir
                    ); ?>

                    <?= $form->field($modelSiswa, 'jurusan')->textInput(['maxlength' => true]) ?>

                    <?=
                        $form->field($modelBioData, 'file')->widget(FileInput::classname(), [
                            'options' => [
                                'allowedFileExtensions' => ['jpg', 'gif', 'png', 'bmp'],
                            ],
                            'language' => 'en',
                            'pluginOptions' => [
                                'browseClass' => 'btn btn-success',
                                'browseLabel' =>  'Unggah',
                                'showPreview' => true,
                                'showCaption' => true,
                                'showRemove' => true,
                                'showUpload' => false,
                                'required'=>true,
                            ],
                        ])->label('Foto')?>

                    

                    <div class="form-group">
                        <?= Html::submitButton($modelUser->isNewRecord ? 'Create' : 'Update', ['class' => $modelUser->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    </div>

                    <!-- END Register Form -->
                </div>
            </div>
                    <?php ActiveForm::end(); ?>
        </div>
        <!-- Register Form -->
        
        <!-- END Register Block -->

        <!-- Footer -->
        <footer class="text-muted text-center animation-pullUp">
            <small><span id="year-copy"></span> &copy; <a href="http://goo.gl/RcsdAh" target="_blank">AppUI 2.9</a></small>
        </footer>
        <!-- END Footer -->
    </div>
    

</div>