models/Coach.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "coach".
 *
 * @property int $id
 * @property int $id_user
 * @property string $status_menikah
 * @property string $kewarganegaraan
 * @property string $pendidikan
 * @property int $status 1 = aktif; 0 = gak aktif
 *
 * @property AbsensiCoach[] $absensiCoaches
 * @property User $user
 * @property Jadwal[] $jadwals
 */
class Coach extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'coach';
    }   
    const PATH_ = 'web/upload/coach/';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'status_menikah', 'kewarganegaraan', 'pendidikan', 'status'], 'required'],
            [['id_user', 'status'], 'integer'],
            [['pendidikan'], 'string'],
            [['status_menikah'], 'string', 'max' => 15],
            [['kewarganegaraan'], 'string', 'max' => 20],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id_user']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'status_menikah' => 'Status Menikah',
            'kewarganegaraan' => 'Kewarganegaraan',
            'pendidikan' => 'Pendidikan',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbsensiCoaches()
    {
        return $this->hasMany(AbsensiCoach::className(), ['id_coach' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_user' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwals()
    {
        return $this->hasMany(Jadwal::className(), ['id_coach' => 'id']);
    }
    
    public function getPathFoto()
    {
        return $this->user->biodataUsers->foto;
    }

    public function getClassLabel($value='')
    {
        if ($this->status == 0) {
            return 'primary';
        }elseif ($this->status ==1) {
            return 'success';
        }else{
            return 'danger';
        }    
    }

    public function getStatusString()
    {
        if ($this->status == 0) {
            return 'Proses';
        }elseif ($this->status ==1) {
            return 'Aktif';
        }else{
            return 'Tidak Aktif';
        }
    }
}

models/Pembayaran.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "pembayaran".
 *
 * @property int $id
 * @property int $id_siswa
 * @property double $nominal
 * @property string $jenis
 * @property string $catatan
 * @property string $status
 * @property string $bukti_transfer
 *
 * @property Siswa $siswa
 */
class Pembayaran extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pembayaran';
    }

    public $file;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_siswa', 'nominal', 'jenis', 'catatan', 'status', 'bukti_transfer', 'atas_nama'], 'required'],
            [['id_siswa'], 'integer'],
            [['nominal'], 'number'],
            [['catatan', 'atas_nama'], 'string'],
            [['file'], 'file', 'extensions' => 'gif, jpg, jpeg, png'],
            [['jenis'], 'string', 'max' => 50],
            [['status'], 'string', 'max' => 20],
            [['bukti_transfer'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_siswa' => 'Id Siswa',
            'Nominal' => 'Nominal',
            'jenis' => 'Jenis',
            'catatan' => 'Catatan',
            'status' => 'Status',
            'atas_nama'=>'Atas Nama',
            'bukti_transfer' => 'Bukti Transfer',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswa()
    {
        return $this->hasOne(Siswa::className(), ['id' => 'id_siswa']);
    }

    public function getPath()
    {
        return $this->bukti_transfer;
    }

    public function getType()
    {
        return [
            'tunai' => 'Tunai',
            'transfer' => 'Transfer',
            'lain-lain'=> 'Lain-Lain'
        ];
    }

    public static function getIdUser(){
        return Yii::$app->user->identity->id;
    }

    public static function getIdSiswa($value='')
    {
        return Yii::$app->user->identity->siswas->id;
    }
}

controllers/PembayaranController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pembayaran;
use app\models\Siswa;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
/**
 * PembayaranController implements the CRUD actions for Pembayaran model.
 */
class PembayaranController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pembayaran models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataBelum = Pembayaran::find()->where(['status'=>0])->all();
        $dataSudah = Pembayaran::find()->where(['status'=>1])->all();

        return $this->render('index', [
            'dataBelum' => $dataBelum,
            'dataSudah' => $dataSudah,
        ]);
    }

    /**
     * Displays a single Pembayaran model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pembayaran model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pembayaran();

        if ($model->load(Yii::$app->request->post())) {

            $file = UploadedFile::getInstance($model, 'file');
            $timeFile = strtotime("now");
            $path = Siswa::PATH_.$model->getIdUser();
            FileHelper::createDirectory($path, $mode = 0775, $recursive = true);
            $namaFile = $model->getIdUser().'-'.$timeFile; 
            $file->saveAs($path ."/". $namaFile . '.' . $file->extension);
            $model->bukti_transfer = $path ."/". $namaFile . '.' . $file->extension;
            $model->status = 0;
            $model->id_siswa = $model->getIdSiswa();
            $model->save(false);

            $modelSiswa = Siswa::findOne($model->getIdSiswa());
            $modelSiswa->status='membayar';
            $modelSiswa->save(false);

            \Yii::$app->getSession()->setFlash('success', 'Saved');
            return $this->redirect(['create']);
        }else{
            return $this->render('create', [
                'model' => $model,
            ]);
            
        }

    }

    public function actionVerifikasi($id)
    {
        $model = $this->findModel($id);
        $model->status =1;
        $model->save(false);
        $modelSiswa = Siswa::findOne($model->id_siswa);
        $modelSiswa->status = 'peserta';
        $modelSiswa->save(false);
        \Yii::$app->getSession()->setFlash('success', 'Saved');
        return $this->redirect(['index']);
    }

    /**
     * Updates an existing Pembayaran model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pembayaran model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pembayaran model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pembayaran the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pembayaran::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/pembayaran/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
/* @var $this yii\web\View */
/* @var $model app\models\Pembayaran */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php
        foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
            echo '<div class="alert alert-' . $key . '">' . $message . '</div>';
        }
    ?>
        <!-- END Horizontal Form Title -->

        <!-- Horizontal Form Content -->
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'nominal')->textInput() ?>

        <?= $form->field($model, 'jenis')->dropDownList(
                $model->getType()
        ); ?>

        <?= $form->field($model, 'catatan')->textarea(['rows' => 6]) ?>

        <?= $form->field($model, 'file')->widget(FileInput::classname(), [
                            'options' => [
                                'allowedFileExtensions' => ['jpg', 'gif', 'png', 'bmp'],
                            ],

                            'language' => 'en',
                            'pluginOptions' => [
                                'browseClass' => 'btn btn-success',
                                'browseLabel' =>  'Unggah',
                                'showPreview' => true,
                                'showCaption' => true,
                                'showRemove' => true,
                                'showUpload' => false,
                                'required'  => true
                                // 'mainClass' => 'btn-loginregist'
                            ],
                        ])->label('Bukti Transfer')

            ?>
        <?= $form->field($model, 'atas_nama')->textInput() ?>
        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>
        <!-- END Horizontal Form Content -->

views/pembayaran/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Pembayaran */

$this->title = 'Create Pembayaran';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pembayaran-form">
    <div class="block">
        <!-- Horizontal Form Title -->
        <div class="block-title">
            <h2>Pembayaran</h2>
        </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
    </div>
    

</div>		

views/pembayaran/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use dmstr\bootstrap\Tabs;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Pembayaran';
$this->params['breadcrumbs'][] = $this->title;
// $this->registerJsFile("@web/templates/js/custom.js", ['depends' => 'yii\web\JqueryAsset']);

Modal::begin([
        'header'=>'<h4>Detail Siswa</h4>',
        'id'=>'modal',
        'size'=>'modal-lg',
    ]);
echo "<div id='content-modal'></div>";
Modal::end();
?>

<?php $this->beginBlock('belum'); ?>
<div class="table-responsive">
<table id="example-datatable" class="table table-striped table-bordered table-vcenter">
    <thead>
        <tr>
            <th style="width: 80px;" class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></th>
            <th>Nama</th>
            <th style="width: 80px;">Jenis</th>
            <th>Catatan</th>
            <th style="width: 220px;" class="text-center"><i class="fa fa-flash"></i></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($dataBelum as $key => $value) { 
            $urlView = Url::toRoute(['/pembayaran/view', 'id' => $value->id]);
            $tglUpload = str_replace($value->siswa->getBasePath().$value->siswa->user->id.'/'.$value->siswa->user->id.'-', '', $value->bukti_transfer);
            $tglUpload = explode(".", $tglUpload)[0];
            $tglUpload = date('m/d/Y', $tglUpload);
            $urlVerifikasi = Url::toRoute(['/pembayaran/verifikasi', 'id' => $value->id]);
        ?>
        <tr>
            <td class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></td>
            <td><strong><?=strtoupper($value->siswa->user->biodataUsers->nama)?></strong></td>
            <td><?=strtoupper($value->jenis)?></td>
            <td><?=$value->catatan?></td>
            <td class="text-center">
                <?=Html::button('<i class="fa fa-info-circle"></i>', ['value'=>$urlView,'class' => 'btn btn-primary btn-flat btn-modal btn-sm']);?>
                <?= Html::a('<i class="gi gi-picture"></i>', [$value->bukti_transfer, 'id' => $value->id], ['class' => 'btn btn-default btn-sm', 'data-toggle'=>'lightbox-image', 'title'=>$tglUpload]) ?>
                <?= Html::a('<i class="gi gi-check"></i>', ['verifikasi', 'id' => $value->id], ['class' => 'btn btn-success btn-sm']) ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>
<?php $this->endBlock() ?>

<?php $this->beginBlock('sudah'); ?>
<div class="table-responsive">
<table id="example-datatable" class="table table-striped table-bordered table-vcenter">
    <thead>
        <tr>
            <th style="width: 80px;" class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></th>
            <th>Nama</th>
            <th style="width: 80px;">Jenis</th>
            <th>Catatan</th>
            <th style="width: 120px;" class="text-center"><i class="fa fa-flash"></i></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($dataSudah as $key => $value) { 
            $urlView = Url::toRoute(['/pembayaran/view', 'id' => $value->id]);
            $tglUpload = str_replace($value->siswa->getBasePath().$value->siswa->user->id.'/'.$value->siswa->user->id.'-', '', $value->bukti_transfer);
            $tglUpload = explode(".", $tglUpload)[0];
            $tglUpload = date('m/d/Y', $tglUpload);
        ?>
        <tr>
            <td class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></td>
            <td><strong><?=strtoupper($value->siswa->user->biodataUsers->nama)?></strong></td>
            <td><?=strtoupper($value->jenis)?></td>
            <td><?=$value->catatan?></td>
            <td class="text-center">
                <?=Html::button('<i class="fa fa-info-circle"></i>', ['value'=>$urlView,'class' => 'btn btn-primary btn-flat btn-modal btn-sm']);?>
                <?= Html::a('<i class="gi gi-picture"></i>', [$value->bukti_transfer, 'id' => $value->id], ['class' => 'btn btn-default btn-sm', 'data-toggle'=>'lightbox-image', 'title'=>$tglUpload]) ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>
<?php $this->endBlock() ?>


<div class="pembayaran-index">

    <div class="block full">
        <?php
            foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
                echo '<div class="alert alert-' . $key . '">' . $message . '</div>';
            }
        ?>
        <div class="block-title">
            <h2>Pembayaran Siswa</h2>
        </div>
        

        <?= Tabs::widget(
        [
            'id' => 'relation-tabs',
            'encodeLabels' => false,
            'items' => [ 
                [
                    'label'   => '<b class="">Belum Verifikasi</b>',
                    'content' => $this->blocks['belum'],
                    'active'  => true,
                ],
                [
                    'label'   => '<b class="">Sudah Verifikasi</b>',
                    'content' => $this->blocks['sudah'],
                    'active'  => false,
                ],
            ]
        ]
    );?>
    </div>

</div>
<script src="<?=Yii::$app->homeUrl?>web/templates/js/pages/compGallery.js"></script>
<script>$(function(){ CompGallery.init(); });</script>

views/pembayaran/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pembayaran */

$this->title = 'Update Pembayaran: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pembayarans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pembayaran-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/pembayaran/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pembayaran */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pembayarans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="widget">
            <div class="widget-image widget-image-sm">
                <img src="<?=Yii::$app->homeUrl?>templates/img/placeholders/photos/photo1@2x.jpg" alt="image">
                <div class="widget-image-content text-center">
                    <img src="<?=Yii::$app->homeUrl?>/<?=$model->siswa->pathFoto?>" alt="avatar" class="img-circle img-thumbnail img-thumbnail-transparent img-thumbnail-avatar-2x push">
                    <h2 class="widget-heading text-light"><strong><?=$model->siswa->user->biodataUsers->nama?></strong></h2>
                    <h4 class="widget-heading text-light-op"><em><?=$model->siswa->user->email?></em></h4>
                </div>
            </div>
            <div class="widget-content border-bottom">
               <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'nominal',
                        'jenis',
                        'catatan:ntext',
                    ],
                ]) ?>
            </div>
        </div>
    </div>
</div>