models/Kursus.php
<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "kursus".
 *
 * @property int $id
 * @property int $id_mapel
 * @property string $nama
 * @property string $tanggal_awal
 * @property string $tanggal_akhir
 * @property int $quota
 * @property int $status 1 = dibuka; 2 = sedang ; 3 = ditutup
 *
 * @property Jadwal[] $jadwals
 * @property Mapel $mapel
 * @property SiswaKursus[] $siswaKursuses
 */
class Kursus extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    const DIBUKA = 1;
    const DIBUAT = 0;
    const SEDANG_BERLANGSUNG = 2;
    const DITUTUP = 3;

    public $jadwal;
    public static function tableName()
    {
        return 'kursus';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nama', 'tanggal_awal', 'tanggal_akhir', 'quota', 'status'], 'required'],
            [['quota', 'status'], 'integer'],
            [['tanggal_awal', 'tanggal_akhir'], 'safe'],
            [['nama'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'tanggal_awal' => 'Tanggal Awal',
            'tanggal_akhir' => 'Tanggal Akhir',
            'quota' => 'Quota',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwals()
    {
        return $this->hasMany(Jadwal::className(), ['id_kursus' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMapel()
    {
        return $this->hasOne(Mapel::className(), ['id' => 'id_mapel']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswaKursuses()
    {
        return $this->hasMany(SiswaKursus::className(), ['id_kursus' => 'id']);
    }

    public function saving()
    {
        $this->status = self::DIBUAT;
        return $this->save();
    }

    public function getArrayStatus($value='')
    {
        return [
            self::DIBUKA => 'Dibuka',
            self::SEDANG_BERLANGSUNG=>'Sedang Berlangsung',
            self::DITUTUP =>'Ditutup'
        ];
    }

    public function getArrayDays($value='')
    {
        return [
            'Sun' => 'Minggu',
            'Mon' =>'Senin',
            'Tue' =>'Selasa',
            'Wed' =>'Rabu',
            'Thu' =>'Kamis',
            'Fri' =>'Senin',
            'Sat' =>'Sabtu',
        ];
    }

    public function getArraySelectedDay($array)
    {
        $selected = array();
        $selected['days'] = array();
        $selected['coach'] = array();
        $selected['room'] = array();
        $selected['start'] = array();
        $selected['end'] = array();
        foreach ($array as $key => $value) {
            array_push($selected['days'], $value['days']);
            array_push($selected['coach'], $value['coach']);
            array_push($selected['room'], $value['ruang']);
            array_push($selected['start'], $value['tahun_awal']);
            array_push($selected['end'], $value['tahun_akhir']);
        }
        return $selected;
    }

    public function getClassLabel($value='')
    {
        if ($this->status == 1) {
            return 'primary';
        }elseif ($this->status ==2) {
            return 'success';
        }else{
            return 'danger';
        }    
    }

    public function getStatusString()
    {
        if ($this->status == 0) {
            return 'Belum Disetujui';
        }
        else if ($this->status == 1) {
            return 'Dibuka';
        }elseif ($this->status ==2) {
            return 'Sedang Berlangsung';
        }else{
            return 'Ditutup';
        }
    }

    public static function getArrayMapel()
    {
        return ArrayHelper::map(Mapel::find()->all(), 'id', 'nama');
    }

    public function getSisaQuota()
    {
        return ($this->quota - count($this->siswaKursuses));
    }
}

models/Siswa.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "siswa".
 *
 * @property int $id
 * @property int $id_user
 * @property string $pendidikan_terakhir
 * @property string $jurusan
 * @property string $status 'mendaftar, diterima,proses, lulus'
 *
 * @property AbsensiSiswa[] $absensiSiswas
 * @property Pembayaran[] $pembayarans
 * @property User $user
 * @property SiswaKursus[] $siswaKursuses
 */
class Siswa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'siswa';
    }

    public $fotoKtp;

    const PATH_ = 'web/upload/siswa/';
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'pendidikan_terakhir', 'jurusan', 'status'], 'required'],
            [['id_user'], 'integer'],
            [['pendidikan_terakhir', 'status', 'foto_ktp'], 'string', 'max' => 20],
            [['jurusan'], 'string', 'max' => 50],
            [['fotoKtp'], 'file',  'extensions' => 'gif, jpg, jpeg, png'],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id_user']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'pendidikan_terakhir' => 'Pendidikan Terakhir',
            'jurusan' => 'Jurusan',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbsensiSiswas()
    {
        return $this->hasMany(AbsensiSiswa::className(), ['id_siswa' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getPembayarans()
    {
        return $this->hasMany(Pembayaran::className(), ['id_siswa' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_user' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiswaKursuses()
    {
        return $this->hasMany(SiswaKursus::className(), ['id_siswa' => 'id']);
    }

    public function getPathButktiBayar()
    {
        return $this->getPembayarans();
    }

    public function getPathFoto()
    {
        return $this->user->biodataUsers->foto;
    }

    public function getBasePath()
    {
        return self::PATH_;
    }

    public function getNamaSiswa()
    {
        return $this->user->biodataUsers->nama;
    }

    public function getArrayPendidikanTerakhir()
    {
        return [
            'SMA/SMK sederajat' => 'SMA/SMK sederajat',
            'diploma' =>'Diploma',
            'sarjana' =>'Sarjana',
            'Wed' =>'Rabu',
            'magister' =>'Magister',
        ];
    }

    public function checkWaktuPembayaran($value='')
    {
        $model = SiswaKursus::find()->where(['id_siswa'=>User::getIdSiswa()])->orderBy(['id'=> SORT_DESC])->one();
        $currentDate = date('Y-m-d');
        $currentDate=date_create($currentDate);
        $startDate=date_create($model->tgl_pilih);
        $diff=date_diff($currentDate,$startDate);
        if ($diff->d < 3) {
            return true;
        }else{
            return false;
        }
    }

    public function getSisaWaktuPembayaran()
    {
        $model = SiswaKursus::find()->where(['id_siswa'=>User::getIdSiswa()])->orderBy(['id'=> SORT_DESC])->one();
        $currentDate = date('Y-m-d');
        $currentDate=date_create($currentDate);
        $startDate=date_create($model->tgl_pilih);
        return date_diff($currentDate,$startDate)->d;
    }
}

controllers/KursusController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kursus;
use app\models\AbsensiCoach;
use app\models\AbsensiSiswa;
use app\models\Jadwal;
use app\models\User;
use app\models\Siswa;
use app\models\SiswaKursus;
use app\models\Search\Kursus as KursusSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
/**
 * KursusController implements the CRUD actions for Kursus model.
 */
class KursusController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kursus models.
     * @return mixed
     */
    public function actionIndex()
    {

        if (User::getType()==2 ) {
            if (User::getStatusSiswa()=='peserta' || User::getStatusSiswa()=='memilih kursus') {
                $arrayIdKursus = SiswaKursus::find()->select('id_kursus')->where(['id_siswa'=>User::getIdSiswa()])->distinct()->asArray()->all();
                $arrTemp = array();
                foreach ($arrayIdKursus as $key => $value) {
                    $arrTemp[$key]=$value['id_kursus'];
                }
                $query = Kursus::find()->where(['in', 'id', $arrTemp]);
            }else{
                $query = Kursus::find()->where(['status'=>1 ]);
            }
        }else if (User::getType()==3) {
            $arrJadwal = Jadwal::find()->select('id_kursus')->where(['id_coach'=>User::getIdCoach()])->distinct()->asArray()->all();
            $arrTemp = array();
            foreach ($arrJadwal as $key => $value) {
                $arrTemp[$key]=$value['id_kursus'];
            }
            $query = Kursus::find()->where(['in', 'id', $arrTemp]);
        }else{
            $query = Kursus::find();
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('index', [
            'dataKursus' => $dataProvider->getModels(),
        ]);
    }

    /**
     * Displays a single Kursus model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {   
        $modelJadwal = Jadwal::find()->where(['id_kursus'=>$id]);

        if (User::getType()==3) {
            $modelJadwal = Jadwal::find()->where(['id_kursus'=>$id])->andWhere(['id_coach'=>User::getIdCoach()]);
        }
        if (User::getType() == 1 || User::getType() == 3) {
            return $this->render('view', [
                'model' => $this->findModel($id),
                'modelJadwal'=>$modelJadwal->all()
            ]);
        }elseif(User::getType() == 4){
            return $this->render('view', [
                'model' => $this->findModel($id),
                'modelJadwal'=>$modelJadwal->all(),
                'dataSiswaKursus'=>SiswaKursus::find()->where(['id_kursus'=>$id])->all()
            ]);
        }else{
            return $this->renderAjax('view', [
                'model' => $this->findModel($id),
                'modelJadwal'=>$modelJadwal->all()
            ]);
        }
    }

    public function actionUpdateJadwal($id)
    {   
        $modelJadwal = Jadwal::findOne($id);

        if ($modelJadwal->load(Yii::$app->request->post())) {
            $modelJadwal->waktu_mulai = date("H:i", strtotime($modelJadwal->waktu_mulai));
            $modelJadwal->waktu_selesai = date("H:i", strtotime($modelJadwal->waktu_selesai));
            $modelJadwal->save();
            return $this->redirect(['view', 'id'=>$modelJadwal->id_kursus]);
        }else{
            $modelJadwal->waktu_mulai = date('h:i:s a m/d/Y', strtotime($modelJadwal->waktu_mulai));;
            $modelJadwal->waktu_selesai = date('h:i:s a m/d/Y', strtotime($modelJadwal->waktu_selesai));;
            return $this->renderAjax('_form_jadwal', [
                'modelJadwal'=>$modelJadwal
            ]);
            
        }
    }

    public function actionPilihKursus($idKursus)
    {
        $model = new SiswaKursus();
        $model->id_siswa = User::getIdSiswa();
        $model->id_kursus = $idKursus;
        $model->tgl_pilih = date("Y-m-d");
        $model->save();
        $modelSiswa = Siswa::findOne(User::getIdSiswa());
        $modelSiswa->status = 'memilih kursus';
        $modelSiswa->save(false);
        \Yii::$app->getSession()->setFlash('success', 'Data Tersimpan');
        return $this->redirect(['index']);
    }

    /**
     * Creates a new Kursus model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Kursus();
        $modelJadwal = new Jadwal();
        // print_r($model->arrayMapel);
        if ($model->load(Yii::$app->request->post()) ) {
            $modelJadwal->load(Yii::$app->request->post());
            $countJadwal =count(Yii::$app->request->post('coach'));
            
            $model->tanggal_awal = $modelJadwal['hari'][0];
            $model->tanggal_akhir = $modelJadwal['hari'][$countJadwal-1];
            $model->saving();
            for ($i=0; $i < $countJadwal; $i++) { 
                $newModelJadwal = new Jadwal();
                $newModelJadwal->id_kursus = $model->id;
                $newModelJadwal->id_coach = Yii::$app->request->post()['coach'][$i];
                $newModelJadwal->waktu_mulai = $modelJadwal['waktu_mulai'][$i];
                $newModelJadwal->waktu_selesai = $modelJadwal['waktu_selesai'][$i];
                $newModelJadwal->hari = $modelJadwal['hari'][$i];
                $newModelJadwal->mapel = $modelJadwal['mapel'][$i];
                $newModelJadwal->id_ruangan = Yii::$app->request->post()['ruangan'][$i];
                $newModelJadwal->save();
            }
            \Yii::$app->getSession()->setFlash('success', 'Saved');
            return $this->redirect(['index']);
        }

        return $this->renderAjax('create', [
            'model' => $model,
            'modelJadwal'=>$modelJadwal
        ]);
    }


    public function actionViewAbsensi($idJadwal)
    {
        $dataAbsensi = AbsensiSiswa::find()->where(['id_jadwal'=>$idJadwal])->all();
        return $this->renderAjax('view_absensi',[
            'dataAbsensi'=>$dataAbsensi,
        ]);
    }

    public function actionViewSiswa($idKursus, $idJadwal)
    {
        $dataSiswa = SiswaKursus::find()->where(['id_kursus'=>$idKursus])->all();

        return $this->renderAjax('view_siswa',[
            'dataSiswa'=>$dataSiswa,
            'idJadwal'=>$idJadwal,
            'idKursus'=>$idKursus
        ]);
    }

    public function actionSaveAbsensi()
    {
        $idSiswa = Yii::$app->request->post('absensi');
        $idJadwal = Yii::$app->request->post('id_jadwal');
        $idKursus = Yii::$app->request->post('id_kursus');
        $modelAbsensiCoach = new AbsensiCoach();
        $modelAbsensiCoach->id_coach = User::getIdCoach();
        $modelAbsensiCoach->keterangan = 'h';
        $modelAbsensiCoach->id_jadwal = $idJadwal;
        $modelAbsensiCoach->save();

        $dataSiswa = SiswaKursus::find()->where(['id_kursus'=>$idKursus])->all();

        foreach ($dataSiswa as $key => $value) {
            $modelAbsensiSiswa = new AbsensiSiswa();
            $modelAbsensiSiswa->id_siswa = $value->id_siswa;
            $modelAbsensiSiswa->keterangan = in_array($value->id_siswa, $idSiswa) ? 'h':'i'; 
            $modelAbsensiSiswa->id_jadwal = $idJadwal;
            echo in_array($value->id_siswa, $idSiswa) ? 'h':'i';
            $modelAbsensiSiswa->save();
        }
        return $this->redirect(['view', 'id'=>$idKursus]);
    }

    public function actionSetujuiKursus($idKursus)
    {
        $modelKursus = $this->findModel($idKursus);
        $modelKursus->status = 1; 
        $modelKursus->save();
        \Yii::$app->getSession()->setFlash('success', 'Data Tersimpan');
        return $this->redirect(['view', 'id'=>$idKursus]);
    }
    /**
     * Updates an existing Kursus model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Kursus model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Kursus model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kursus the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kursus::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/kursus/_form_jadwal.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\time\TimePicker;
use kartik\date\DatePicker;
use unclead\multipleinput\MultipleInput;
/* @var $this yii\web\View */
/* @var $model app\models\Kursus */
/* @var $form yii\widgets\ActiveForm */

$this->registerJsFile("@web/web/templates/js/pages/formsWizard.js", ['depends' => 'yii\web\JqueryAsset']);
$this->registerCssFile("@web/web/templates/css/custom.css");
?>

<?php $form = ActiveForm::begin([
        'id' => 'clickable-wizard',
    ]); ?>
    <?= $form->field($modelJadwal, 'id_coach')->widget(Select2::classname(), [
        'data' => $modelJadwal->kursus->getArrayCoach(),
        'options' => ['placeholder' => 'Pilih Coach'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($modelJadwal, 'id_ruangan')->widget(Select2::classname(), [
        'data' => $modelJadwal->kursus->getArrayRuang(),
        'options' => ['placeholder' => 'Pilih Ruangan'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($modelJadwal, 'waktu_mulai')->widget(TimePicker::classname(), [
        'options' => ['placeholder' => 'Pilih Ruangan'],
        'pluginOptions' => [
            'showSeconds' => true
        ],
    ]); ?>

    <?= $form->field($modelJadwal, 'waktu_selesai')->widget(TimePicker::classname(), [
        'options' => ['placeholder' => 'Pilih Ruangan'],
        'pluginOptions' => [
            'showSeconds' => true
        ],
    ]); ?>
    <button type="submit" class="btn btn-effect-ripple btn-primary" id="next1">Next</button>
<?php ActiveForm::end(); ?>

views/kursus/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Kursus */

$this->title = 'Create Kursus';
$this->params['breadcrumbs'][] = ['label' => 'Kursuses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kursus-create">
    <?= $this->render('_form', [
        'model' => $model,
        'modelJadwal'=>$modelJadwal

    ]) ?>

</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('.modal-header').html('<h4>Create Kursus<h4>');
    });
</script>

views/kursus/index.php
<?php

use yii\helpers\Html;
use app\models\User;
use app\models\Siswa;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel app\models\Search\Kursus */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Kursus';
$this->params['breadcrumbs'][] = $this->title;
Modal::begin([
        'header'=>'<h4>Create Kursus</h4>',
        'id'=>'modal',
        'size'=>'modal-lg',
        'options' => [
            'tabindex' => false // important for Select2 to work properly
        ],
    ]);
echo "<div id='content-modal'></div>";
Modal::end();

// $this->registerJsFile("@web/templates/js/custom.js", ['depends' => 'yii\web\JqueryAsset']);
// $this->registerJsFile("@web/templates/js/form.js", ['depends' => 'yii\web\JqueryAsset']);
// $this->registerJsFile("@web/templates/js/pages/uiTables.js", ['depends' => 'yii\web\JqueryAsset']);

$urlCreate = Url::toRoute(['/kursus/create']);
?>
<div class="coach-index">
    <?php if (User::getType()==2 && User::getStatusSiswa()=='memilih kursus') { ?>
        <?php if (Siswa::checkWaktuPembayaran()) {?>        
            <div class="row">
                <a href="javascript:void(0)" class="widget">
                    <div class="widget-content themed-background-danger text-light-op text-center">
                        Batas Pembayaran Anda Tinggal
                        <strong><?= Siswa::getSisaWaktuPembayaran()?> Hari Lagi</strong>
                    </div>
                </a>
            </div>
            <?= Html::a('Upload Bukti Pembayaran', ['/pembayaran/create'], ['class' => 'btn btn-success']) ?>
        <?php }?>
        <?= Html::a('Ganti Kursus', ['view', 'id' => 1], ['class' => 'btn btn-danger']) ?>
    <?php } ?>
    <?php if (User::getType()==1){?>
        <?=Html::button('<i class="fa fa-plus"></i>', ['value'=>$urlCreate,'class' => 'btn btn-primary btn-flat btn-modal btn-sm']);?>
    <?php } ?>
    <div class="block full">
        <?php
            foreach (Yii::$app->session->getAllFlashes() as $key => $message) {
                echo '<div class="alert alert-' . $key . '">' . $message . '</div>';
            }
        ?>
        <div class="block-title">
            <h2>Datatables</h2>
        </div>
        <div class="table-responsive">
            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 50px;">ID</th>
                        <th>Nama</th>
                        <th style="width: 50px;">Kuota</th>
                        <th style="width: 250px;">Periode</th>
                        <th style="width: 50px;">Status</th>
                        <th class="text-center" style="width: 80px;"><i class="fa fa-flash"></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dataKursus as $key => $value) { 
                        $urlUpdate = Url::toRoute(['/kursus/update', 'id' => $value->id]);
                        $urlViewJadwal = Url::toRoute(['/kursus/view', 'id' => $value->id]);
                    ?>
                    <tr>
                        <td class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox"><span></span></label></td>
                        <td><strong><?=strtoupper($value->nama)?></strong></td>
                        <td><?=$value->quota?></td>
                        <td><b><?=Yii::$app->formatter->asDate($value->tanggal_awal, 'dd MMMM Y')?></b> s/d <b> <?=Yii::$app->formatter->asDate($value->tanggal_akhir, 'dd MMMM Y')?></b></td>
                        <td><span class="label label-<?=$value->classLabel?>"><?=$value->statusString?></span></td>
                        <td class="text-center">
                            <?php if (User::getType()==2){ ?>
                                <?=Html::button('<i class="fa fa-eye"></i>', ['value'=>$urlViewJadwal,'class' => 'btn btn-effect-ripple btn-xs btn-primary btn-modal']);?>
                            <?php }else{?>
                                <?php if (User::getType()==1 && $value->status !=0) {?>
                                    <?=Html::button('<i class="fa fa-pencil"></i>', ['value'=>$urlUpdate,'class' => 'btn btn-effect-ripple btn-xs btn-primary btn-modal']);?>
                                    <?= Html::a('<i class="fa fa-times"></i>', ['delete', 'id' => $value->id], [
                                        'class' => 'btn btn-effect-ripple btn-xs btn-danger',
                                         'data' => [
                                            'confirm' => 'Are you sure you want to delete this item?',
                                            'method' => 'post',
                                        ],]) ?>
                                <?php } ?>
                                <?= Html::a('<i class="fa fa-eye"></i>', ['view', 'id' => $value->id], [
                                    'class' => 'btn btn-effect-ripple btn-xs btn-success']) ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script>$(function(){ UiTables.init(); });</script>

views/kursus/view_absensi.php
<?php 
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\Jadwal;
?>

<div class="siswa-index">
    <div class="block full">
        <div class="block-title">
            <h2>Datatables</h2>
        </div>
        <div class="table-responsive">
            <table id="myTable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Keterangan</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dataAbsensi as $key => $value) { 
                    ?>
                    <tr>
                        <td><strong><?=strtoupper($value->siswa->namaSiswa)?></strong></td>
                        <td><?= ($value->keterangan == 'h') ? '<span class="label label-success"><i class="fa fa-check"></i></span>' : '<span class="label label-danger"><i class="fa fa-times"></i></span>'?></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>    
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable();
    } );
</script>

views/kursus/view_siswa.php
<?php 
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use app\models\Jadwal;
?>


<?php $form = ActiveForm::begin([
        'id' => 'clickable-wizard',
        'action'=>['save-absensi']
]); ?>

<?php if (Jadwal::getCheckAbsensi($idJadwal)) { ?>
    <i>Data telah Tersimpan</i>
<?php }else{ ?>

<input type="hidden" name="id_jadwal" value="<?=$idJadwal?>">
<input type="hidden" name="id_kursus" value="<?=$idKursus?>">
<div class="siswa-index">
    <div class="block full">
        <div class="block-title">
            <h2>Datatables</h2>
        </div>
        <div class="table-responsive">
            <table id="myTable" class="table table-striped table-bordered table-vcenter">
                <thead>
                    <tr>
                        <th style="width: 80px;" class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox" checked="true"><span></span></label></th>
                        <th>Nama</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dataSiswa as $key => $value) { 
                    ?>
                    <tr>
                        <td class="text-center"><label class="csscheckbox csscheckbox-primary"><input type="checkbox" name="absensi[]" value="<?=$value->siswa->id?>"><span></span></label></td>
                        <td><strong><?=strtoupper($value->siswa->namaSiswa)?></strong></td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>    
</div>
<?php ActiveForm::end(); ?>
<?php } ?>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready( function () {
        $('#myTable').DataTable();
        $('input:checkbox').each(function() {
            $(this).prop('checked', true);
        });

    } );
</script>